### ISSUE TITLE
Missing documenation page - automatic configuration

### ISSUE THREAD

**Issue by emil45** [launchdarkly/ld-relay#107]
In the README there is a link to automatic configuration - but it's broken, I get 404.

https://docs.launchdarkly.com/home/advanced/relay-proxy/automatic-configuration

**Comment by bwoskow-ld** [comment]
Hi @emil45,

The LaunchDarkly engineering team identified an issue with the automatic configuration feature implementation in the LaunchDarkly service. We plan to resolve this issue before publishing the documentation. Apologies for the confusion! I'll comment here when the feature and documentation are live.

Cheers,
Ben

**Comment by emil45** [comment]
Thanks, I'm waiting.

**Comment by bwoskow-ld** [comment]
The feature and documentation are now available. Thanks for waiting!
