### ISSUE TITLE
Invalid SDK key when starting up relay host via Docker or from source

### ISSUE THREAD

**Issue by lanerfy182** [launchdarkly/ld-relay#110]
Hi,

This issue is what I encountered when setting up the launchdarkly relay host via Docker or from source. I get errors upon following the steps provided. I get stuck on a similar invalid SDK error. I am running it on an Ubuntu instance. 

![image](https://user-images.githubusercontent.com/55248717/98387810-da01e680-208c-11eb-943c-8d26dffaf3f3.png)

I am new to launchdarkly and would like to test the relay host. Thanks.

**Comment by hroederld** [comment]
Hi @lanerfy182 

Did you take the screenshot intentionally without your SDK key, or did you paste the documentation example directly? You must set the value of `LD_ENV_test` to a valid SDK key. You can find correct value by copying "SDK key" from the LaunchDarkly dashboard at https://app.launchdarkly.com/settings/projects the result should be something like `-e LD_ENV_test="sdk-28e1c7d6-0373-4ee4-9995-236f3fed7f19"` (this is a fake key).

**Comment by eli-darkly** [comment]
Also, please try not to use this issue tracker for basic support requests. This is for reporting bugs in the Relay Proxy code; we can try to answer questions, but we're the developers who maintain the code. The support team is [here](https://support.launchdarkly.com/hc/en-us).

**Comment by hroederld** [comment]
Hi @lanerfy182 I'm going to close this issue now. If you are still having issues getting started please contact support. If you find a legitimate bug feel free to open another issue.
