### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by amitsaha** [launchdarkly/ld-relay#115]
Consider a setup where a relay is configured to use a persistent store and is being deployed along with the application as a side-car either in a VM or a pod. 

At startup, the relay is opening up its communication channels with Redis and launchdarkly.com. There is quite a bit of initial bootstrapping that i assume is happening in the relay during these first seconds at startup. 

Does the relay have a healthcheck endpoint that another service can ping to ensure that the relay is ready to serve flag requests? That is, once all the initialisation has been happened.

**Comment by bwoskow-ld** [comment]
Hi @amitsaha ,

Check out https://github.com/launchdarkly/ld-relay/blob/v6/docs/endpoints.md#status-health-check to learn about Relay's health check endpoint.

Cheers,
Ben

**Comment by amitsaha** [comment]
Ah 🤦 thank you.

**Comment by bwoskow-ld** [comment]
Any time!
