### ISSUE TITLE
Benchmarking/Performance based on the flag size/rules

### ISSUE THREAD

**Issue by amitsaha** [launchdarkly/ld-relay#121]
The relay proxy docs have this:

> The Relay Proxy's resource usage increases based on the size of your flags or segments, number of SDK connections, and events it proxies.

Do we have any way currently benchmark the ld-relay process (mostly to understand resource usage) by generating synthetic flag data?

**Comment by bwoskow-ld** [comment]
Hi @amitsaha ,

Take a look at our ["Testing Relay Proxy performance" documentation](https://docs.launchdarkly.com/home/advanced/relay-proxy/performance). That page describes how to do exactly what you are looking for.
