### ISSUE TITLE
Relay Proxy DynamoDB Access with AWS IRSA

### ISSUE THREAD

**Issue by juanjbrown** [launchdarkly/ld-relay#127]
**Is your feature request related to a problem? Please describe.**
Hi. We'd like to run the Relay Proxy in EKS with DynamoDB through AWS's [IRSA (IAM roles for service accounts)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), which requires at minimum version 1.23.13 (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html).

**Describe the solution you'd like**
We believe that upgrading the AWS SDK to an IRSA support version would address this.

**Describe alternatives you've considered**
* Pull request upgrading the AWS SDK version
* Deploying the Relay Proxy with a sidecar pod that works with IRSA and mounts the role session credentials in a way the Relay Proxy's current SDK version can use

**Comment by eli-darkly** [comment]
Thanks for bringing this to our attention. This should be an easy update, but please see my comment on the PR regarding the choice of version.

**Comment by eli-darkly** [comment]
We've released version 6.1.5 with this update. Please let us know when you've had a chance to try it.
