### ISSUE TITLE
Please use Go compatible version tags.

### ISSUE THREAD

**Issue by alecthomas** [launchdarkly/ld-relay#131]
Go version tags must have `v` as the prefix. The last valid tagged version that adheres to this is v6.0.3. Correctly tagging versions will help us track ld-relay versions correctly.

**Comment by bwoskow-ld** [comment]
Hi @alecthomas ,

You're right that we hadn't published tags compatible with Go modules for our 6.1.0 - 6.1.5 releases. I published the missing tags just now and will update our release automation to include this moving forward.

Cheers,
@bwoskow-ld

**Comment by alecthomas** [comment]
Cheers, thank you.
