### ISSUE TITLE
Thanks for noticing the broken link, but your replacement link is also broken: `configuration.md` is in the same directory as `metrics.md`, so this should be a single period and not a double one.

### ISSUE THREAD

**Issue by ghost** [launchdarkly/ld-relay#158]
Thanks for noticing the broken link, but your replacement link is also broken: `configuration.md` is in the same directory as `metrics.md`, so this should be a single period and not a double one.

_Originally posted by @eli-darkly in https://github.com/launchdarkly/ld-relay/pull/135#r619377810_

**Comment by eli-darkly** [comment]
It looks like this issue was filed by mistake, or at least does not have a useful description. The quoted comment has already been addressed.
