### ISSUE TITLE
Support passing an environment variable for REDIS_USERNAME

### ISSUE THREAD

**Issue by chrisjgray** [launchdarkly/ld-relay#167]
**Is your feature request related to a problem? Please describe.**
With Redis 6, there is now support for RBAC, with multiple users and passwords. Please support adding REDIS_USERNAME instead of having to rely on passing the REDIS_URL.

**Describe the solution you'd like**
Additional option to pass REDIS_USERNAME to dynamically generate the Redis Url.

**Describe alternatives you've considered**
Alternative is to just use the REDIS_URL.

**Additional context**

**Comment by eli-darkly** [comment]
That's reasonable. (Filed internally as 140358)

**Comment by cwaldren-ld** [comment]
Hi @chrisjgray, thank you for this request. This has been added in [7.1.0](https://github.com/launchdarkly/ld-relay/releases/tag/v7.1.0).
