### ISSUE TITLE
ARM64 Docker Image

### ISSUE THREAD

**Issue by jordanfelle** [launchdarkly/ld-relay#188]
**Is your feature request related to a problem? Please describe.**
Currently docker images are only built for AMD64.

**Describe the solution you'd like**
Docker images pushed to docker hub would be available for at least AMD64 and ARM64

**Comment by louis-launchdarkly** [comment]
Hello @jordanfelle, we have received your request. Currently, we are looking at the goreleaser tool that we use to create releases to Docker and figuring out the capability.

In the meantime, if you have time, can you try building the relay for AMD64 with the source code and see does that work for you? If you can verify that building for ARM64 is working, that would be one less obstacle for us to publish an ARM64 Docker Image.

**Comment by jordanfelle** [comment]
I spun up a c7g instance and was able to build for ARM64 without any issues, I just started it up with a dummy conf but no errors were seen.

**Comment by louis-launchdarkly** [comment]
@jordanfelle Thank you for testing it out!

**Comment by louis-launchdarkly** [comment]
_Filed Internally as 156011_ after investigation.

**Comment by xocasdashdash** [comment]
@louis-launchdarkly is there any recent update on this? just to get an idea of what's the priority

**Comment by dac-humi** [comment]
Same.

<img width="595" alt="Screen Shot 2022-08-03 at 1 39 02 PM" src="https://user-images.githubusercontent.com/107492010/182673576-0e10d058-eefe-4f88-be05-dff10b135590.png">

**Comment by or-shachar** [comment]
friendly bump 🙏

**Comment by cwaldren-ld** [comment]
Thanks for your patience, this is still on our roadmap.

**Comment by xocasdashdash** [comment]
any new update? I see that the project uses goreleaser so it should be possible to use that to push multiarch images too

**Comment by cwaldren-ld** [comment]
CircleCI has very recently (I believe last week) added support for M1 executors, so we should be able to test it properly now (for darwin) - previously, we could not. This is still on the roadmap; I'm sorry it is taking so long.

**Comment by cwaldren-ld** [comment]
Hi folks, the [v8.3.0](https://github.com/launchdarkly/ld-relay/releases/tag/v8.3.0) release published to [DockerHub ](https://hub.docker.com/r/launchdarkly/ld-relay/)should now contains `armv7` and `arm64v8` images!

Please feel free to test them out, and file any issues you may encounter.
