### ISSUE TITLE
Big segments, seperate DynamoDB tables per environement and autoconfiguration

### ISSUE THREAD

**Issue by hughevans** [launchdarkly/ld-relay#199]
Big segment data does not populate the DynamoDB when you use this configuration combination:

1. Autoconfiguration and supplying `ENV_DATASTORE_TABLE_NAME="table-name-$CID"`
2. `USE_DYNAMODB="true"`

You end up with this in the logs:

```
BigSegmentSynchronizer: Synchronization failed: InvalidParameter: 1 validation error(s) found.
- minimum field size of 3, GetItemInput.TableName.
```

That’s an AWS error from calling DynamoDB GetItem with a blank `TableName`.

I think the issue is that on [this line](https://github.com/launchdarkly/ld-relay/blob/v6/internal/core/bigsegments/store.go#L61) you’re using the table name from `allConfig` and not `envConfig`.

Apart from the big segments everything else has been functioning fine with this Relay Proxy.

Perhaps big segments only works with DynamoDB if you use a single table for all environments?

**Comment by eli-darkly** [comment]
That does look like a mistake - thanks for reporting it. We'll look into it and if that's right, it should be a simple fix that we can release a patch for soon.

**Comment by eli-darkly** [comment]
The [6.7.12](https://github.com/launchdarkly/ld-relay/releases/tag/v6.7.12) release should fix this. I'll close the issue but please feel free to reopen if you still see a similar issue.

**Comment by hughevans** [comment]
Thanks @eli-darkly! Really appreciate the fast response!
