### ISSUE TITLE
Missing Prometheus metrics on LD relay 7.0.0

### ISSUE THREAD

**Issue by carlosjgp** [launchdarkly/ld-relay#209]
**Describe the bug**
No Prometheus metrics generated
requests to `:8031/metrics` return 200 HTTP code but empty body

**To reproduce**
for the file `ld.conf`
```
[Events]
sendEvents = true
[Main]
disableInternalUsageMetrics = true
ignoreConnectionErrors = true
[Prometheus]
enabled = true
port = 8031
```
```
docker run --rm \
  -v "${PWD}/ld.conf:/ldr/ld-relay.conf:ro" \
  -e LD_ENV_test=<SDK KEY> \
  -e LD_PREFIX_test=test\
  -p 8031:8031 \
  launchdarkly/ld-relay:7.0.0
```

```
curl -vvv http://localhost:8031/metrics
*   Trying 127.0.0.1:8031...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8031 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8031
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Wed, 21 Dec 2022 12:19:17 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Expected behavior**
Prometheus metrics are generated

**Logs**
No logs are generated when the request is processed

**SDK version**
N/A

**Language version, developer tools**
N/A

**OS/platform**
Ubuntu 20.04

**Additional context**
N/A

**Comment by eli-darkly** [comment]
Could you please clarify whether this is a new problem you encountered after updating to the latest Relay Proxy release (i.e. it was working for you before with an earlier version), or this is the first time you're using any Relay Proxy version with Prometheus?

**Comment by eli-darkly** [comment]
Also, have you been actually _using_ Relay Proxy (like, making any SDK requests to it)? There won't be any metrics if there hasn't been any usage.

**Comment by carlosjgp** [comment]
This is a new problem we don't have with the `docker.io/launchdarkly/ld-relay:6.7.14`

**Comment by carlosjgp** [comment]
> Also, have you been actually _using_ Relay Proxy (like, making any SDK requests to it)? There won't be any metrics if there hasn't been any usage.

Well, that's a tricky question... If I had metrics saying `total_requests: 0` that would be an easy question to answer

**Comment by eli-darkly** [comment]
@carlosjgp I take your point, but I would think this would also be fairly easy to test. Either you have connected an SDK to this Relay Proxy instance or you haven't.

**Comment by eli-darkly** [comment]
It may seem like a silly question, but we have definitely seen reports of "I don't see any metrics" from people who had simply started the Relay Proxy by itself and done nothing with it other than look for the metrics.

**Comment by carlosjgp** [comment]
We have deployed 7.0.1 in our clusters and we got metrics eventually

Ideally, we would like to see at least 1 metric eg. `_info` with the ld-realy build details... `{version="7.0.1", build="<git rev-parse --short HEAD>"}` so we know that metrics are working
