### ISSUE TITLE
no errors in ld-relay output when redis is down

### ISSUE THREAD

**Issue by kpankonen** [launchdarkly/ld-relay#21]
I have redis stopped but I don't see any errors in stdout/stderr

```
INFO: 2017/08/28 20:51:50 ld-relay.go:82: Starting LaunchDarkly relay version DEV with configuration file /etc/ld-relay.conf
INFO: 2017/08/28 20:51:50 ld-relay.go:248: Listening on port 8030
INFO: 2017/08/28 20:51:50 ld-relay.go:125: Using Redis Feature Store: localhost:6379 with prefix: 
INFO: 2017/08/28 20:51:50 redis.go:63: RedisFeatureStore: Using url: redis://localhost:6379
INFO: 2017/08/28 20:51:50 redis.go:81: RedisFeatureStore: Using prefix: launchdarkly 
INFO: 2017/08/28 20:51:50 redis.go:84: RedisFeatureStore: Using local cache with timeout: 30s
[LaunchDarkly]2017/08/28 20:51:50 Starting LaunchDarkly streaming connection
[LaunchDarkly]2017/08/28 20:51:50 Connecting to LaunchDarkly stream using URL: https://stream.launchdarkly.com/flags
[LaunchDarkly]2017/08/28 20:51:50 Started LaunchDarkly streaming client
[LaunchDarkly]2017/08/28 20:51:50 Successfully initialized LaunchDarkly client!
INFO: 2017/08/28 20:51:50 ld-relay.go:151: Initialized LaunchDarkly client for stage
INFO: 2017/08/28 20:51:50 ld-relay.go:157: Proxying events for environment stage
```

**Comment by ashanbrown** [comment]
@kpankonen I'm scrubbing up our issue backlog.  I know this was a while ago but if this is still a concern of yours, please let us know.  The core of ld relay is just the LaunchDarkly go client.  This client caches flag data is stored in local memory and redis is accessed only if we miss in our local memory cache or we when need to update a value in redis, so it is possible that redis is not being accessed during your operations.  If you aren't seeing errors reported, then that is something we should be able to address in the https://github.com/launchdarkly/go-client repo.

**Comment by ashanbrown** [comment]
Please reopen this issue and let us know more if this is still a problem.  Thanks.
