### ISSUE TITLE
Give us your feedback: Distroless docker image instead of Alpine

### ISSUE THREAD

**Issue by cwaldren-ld** [launchdarkly/ld-relay#224]
We're considering shipping a ["distroless"](https://github.com/GoogleContainerTools/distroless) Docker image (specifically `gcr.io/distroless/static-debian11`) in addition to - and after a deprecation period, instead of - the existing [Alpine-based image](https://hub.docker.com/r/launchdarkly/ld-relay/tags).

The motivation is to reduce the attack surface of the image LaunchDarkly provides. In turn, this should reduce the amount of CVEs reported by tools like Trivy which aren't directly related to Relay itself.

We'd provide both production and [debug versions](https://github.com/GoogleContainerTools/distroless#debug-images) of the image (containing the busybox suite).

Please feel free to comment/emoji if you have any opinion on this potential change. We'd greatly appreciate your input!

**Comment by fzipi360** [comment]
Being a Go service, this just makes sense to me. Distroless is a good choice.

**Comment by cwaldren-ld** [comment]
We are now publishing "distroless" Docker tags, in addition to the existing Alpine tags. They follow the same scheme versioning scheme as the Alpine tags, but have a new suffix. 

You may choose from:
- `-static-debian12-nonroot` (based on gcr.io/distroless/static-debian12:nonroot)
- `-static-debian12-debug-nonroot` (based on gcr.io/distroless/static-debian12:debug-nonroot).

They are about 50% of the size and are available on amd64, armv7, and arm64.

[Check it out!
](https://hub.docker.com/r/launchdarkly/ld-relay/tags)
