### ISSUE TITLE
ld-relay docs say it can load config from environment AND config file, but it doesn't work

### ISSUE THREAD

**Issue by zellyn** [launchdarkly/ld-relay#229]
**Describe the bug**

The configuration docs in [docs/configuration.md](https://github.com/launchdarkly/ld-relay/blob/v7/docs/configuration.md) state:

> * If you pass both `--config` and `--from-env`, it will both load the specified file and use the environment variables. The environment variables will override any equivalent options from the file.
> 
> An example of why you might use both configuration modes together is if you want to deploy a `base.conf` file that contains all of the global configuration for your relay instance, but for security reasons you do not want your SDK key to appear in that file. > Assuming that the name you gave your LaunchDarkly environment in the file is "production", your command line might look like this:
> 
> ```shell
> LD_ENV_production={your_SDK_key} ./ld-relay --config base.conf --from-env
> ```

However, it does not work:

```
# Our config contains the `envId` key/val just to have something:
~/gh/ld-relay v7 cat ld-relay.local.conf                                                                                                           
[Environment "dev"]
  envId = "dev"

# When we try to run with both `-config` and `-from-env`, it doesn't work:
~/gh/ld-relay v7 LD_ENV_dev=$(cat /data/pods/ski-paragon/secrets/launchdarkly-pie-sdk-key) go run ld-relay.go -config ld-relay.local.conf -from-env
2023/03/22 16:51:11.611754 INFO: Starting LaunchDarkly relay version 7.2.1 with configuration file ld-relay.local.conf plus environment variables
2023/03/22 16:51:11.611921 ERROR: Error loading config file: SDK key is required for environment "dev"
exit status 1

# If we keep the environment variable the same, and omit the config file, it does work:
~/gh/ld-relay v7 LD_ENV_dev=$(cat /data/pods/ski-paragon/secrets/launchdarkly-pie-sdk-key) go run ld-relay.go -from-env                  
2023/03/22 16:51:18.680008 INFO: Starting LaunchDarkly relay version 7.2.1 with configuration from environment variables
2023/03/22 16:51:18.680666 INFO: [env: ...1387] Starting LaunchDarkly client 6.0.3
2023/03/22 16:51:18.680885 INFO: [env: ...1387] Starting LaunchDarkly streaming connection
2023/03/22 16:51:18.681305 INFO: Starting server listening on port 8030
2023/03/22 16:51:18.681312 INFO: [env: ...1387] Waiting up to 10000 milliseconds for LaunchDarkly client to start...
2023/03/22 16:51:18.681558 INFO: [env: ...1387] Connecting to LaunchDarkly stream
2023/03/22 16:51:20.879850 INFO: [env: ...1387] LaunchDarkly streaming is active
2023/03/22 16:51:20.879887 INFO: [env: ...1387] Initialized LaunchDarkly client
2023/03/22 16:51:20.879922 INFO: Initialized LaunchDarkly client for "dev"
^Csignal: interrupt
```

The problem seems to be that `ld-relay.go` tries to load the configuration from the file and from the environment completely separately:

* `ld-relay.go` calls `config.LoadConfigFile` [here](https://github.com/launchdarkly/ld-relay/blob/cca0d57d59164e530cd05a685ab1984e5159183e/ld-relay.go#L32)
* `LoadConfigFile` calls `ValidateConfig` [here](https://github.com/launchdarkly/ld-relay/blob/cca0d57d59164e530cd05a685ab1984e5159183e/config/config_from_file.go#L25)
* which ultimately returns an error if the sdk key is missing [here](https://github.com/launchdarkly/ld-relay/blob/cca0d57d59164e530cd05a685ab1984e5159183e/config/config_validation.go#L124)

The behavior the documentation describes is actually useful: it's nice to keep SDK keys out of configuration files, so they can be committed to git.

**Comment by cwaldren-ld** [comment]
Hi @zellyn, I agree this isn't super helpful.

As a workaround, could you try adding a `sdkKey = "placeholder"` to the config, while still setting the environment variable for the SDK key?

_Filed internally as 193866._

**Comment by zellyn** [comment]
Ah, that works. Thanks!
