### ISSUE TITLE
Documentation is inaccurate for `sendEvent` default value

### ISSUE THREAD

**Issue by mbetz08** [launchdarkly/ld-relay#30]
The README documentation says that [sendEvents variable defaults to false](https://github.com/launchdarkly/ld-relay#events), but the value in the go-client's [DefaultConfig for sendEvents is true]( https://github.com/launchdarkly/go-client/blob/v4/ldclient.go#L97)

**Comment by eli-darkly** [comment]
No, those are two different things. The one in the Go SDK means "should the SDK generate analytics events and send them to LaunchDarkly"; that defaults to true. The one in ld-relay means "should ld-relay provide an endpoint that the SDK can send events to, which will then be forwarded to LaunchDarkly"; that defaults to false. The default scenario is therefore that the SDK will generate events, but that it will send them directly to LaunchDarkly without going through the relay.
