### ISSUE TITLE
Precompiled executables

### ISSUE THREAD

**Issue by projectweekend** [launchdarkly/ld-relay#31]
Do you have precompiled executables for this project available for download? I need to deploy this on some servers, and I'd love to just download the executable, rather than install the go tooling to perform a `go get`. Thanks!

**Comment by ashanbrown** [comment]
@projectweekend There are executables posted at https://github.com/launchdarkly/ld-relay/releases.  Let us know if anything is missing.

**Comment by projectweekend** [comment]
Welp, I should have looked there first. Sorry about that. I appreciate the quick response. Thanks!
