### ISSUE TITLE
Support specifying Redis database

### ISSUE THREAD

**Issue by thieman** [launchdarkly/ld-relay#35]
My read of the application as-is is that the Redis pool will always use the default logical database of 0. It may be useful in some cases to specify a different logical database. In our case, our Redis instance is overprovisioned and we'd like to share it across multiple services while isolating each service to its own database to keep things relatively clean.

I think we should be able to alter this line, calling instead to `NewRedisFeatureStoreFromUrl `, and add in a database number (default would still be `0`) specified from environment variables: https://github.com/launchdarkly/ld-relay/blob/5.1.0/relay.go#L224

I could work on throwing this together if it sounds viable.

**Comment by eli-darkly** [comment]
Good point. We'll implement that pretty soon - we're planning to release some other changes to ld-relay this week & should be able to roll this in.

**Comment by eli-darkly** [comment]
This is supported (via a new property that lets you specify a Redis URI) in the [latest release](https://github.com/launchdarkly/ld-relay/releases/tag/5.2.0).
