### ISSUE TITLE
Entrypoint Shell script does not account for Metrics collecting.

### ISSUE THREAD

**Issue by matthalbersma** [launchdarkly/ld-relay#39]
It would be nice if the docker-entrypoint script would build the metric configurations into the config file.

**Comment by ashanbrown** [comment]
@matthalbersma This is a good suggestion. If you have a proposal on how this should work, we'd be happy to look at a PR.  We'd also welcome more information about your use case.  Hopefully we'll get to this in the next few weeks.

**Comment by atrakh** [comment]
Added in [5.4.3](https://github.com/launchdarkly/ld-relay/releases/tag/5.4.3)
