### ISSUE TITLE
Redis URL environemnt variable in entrypoint.sh? 

### ISSUE THREAD

**Issue by lukasmrtvy** [launchdarkly/ld-relay#47]
According to this: https://github.com/launchdarkly/ld-relay/issues/35

Can You update entrypoint.sh to support REDIS_URL env varaible?

And can You provide example of Redis URL ? 
For example:
```
REDIS_URL="redis://:password@host:port/database"
```
Here is info about username in redis URL: https://stackoverflow.com/a/44353927/3797368

**Comment by eli-darkly** [comment]
Yes, we should do that.

**Comment by lukasmrtvy** [comment]
@eli-darkly  PR https://github.com/launchdarkly/ld-relay/pull/48

**Comment by eli-darkly** [comment]
I'm sorry I forgot to update this issue, but this change was included in the v5.5.0 release. Thanks.
