### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by crivabene** [launchdarkly/ld-relay#62]
Hello,

Would it be possible to add the possibility to expose an HTTPS endpoint?

Thanks,
claudio

**Comment by bwoskow-ld** [comment]
Hi Claudio,

Thanks for reaching out with the suggestion. LD Relay currently does not have an HTTPS listener. In the meantime, if you want to interact with LD Relay over HTTPS we recommend that you either use a reverse proxy or put a load balancer in front of the relay.

**Comment by eli-darkly** [comment]
We've finally implemented this in version 5.6.0.
