### ISSUE TITLE
Change Logging level

### ISSUE THREAD

**Issue by vdantuluri** [launchdarkly/ld-relay#66]
How can i change logging level to have detailed logging for debug

**Comment by eli-darkly** [comment]
There isn't currently such a thing as debug-level logging in ld-relay (or in the LaunchDarkly Go SDK). It's a feature we're planning to add in the future.

**Comment by eli-darkly** [comment]
This is identical to issue #51, so I'm closing it. If you'd like to be updated when we do implement this feature, please follow that issue.
