### ISSUE TITLE
Certificate error when starting docker container

### ISSUE THREAD

**Issue by pradeepd12** [launchdarkly/ld-relay#93]
I see this error when trying to start the LD docker container

INFO: [main] Starting LaunchDarkly relay version 5.11.0 with configuration from environment variables
INFO: [env: dev] Starting LaunchDarkly client 4.16.2
INFO: [env: dev] Starting LaunchDarkly streaming connection
INFO: [env: dev] Waiting up to 10000 milliseconds for LaunchDarkly client to start...
INFO: [env: dev] Connecting to LaunchDarkly stream
INFO: [main] Starting server listening on port 8030
WARN: [env: dev] Unable to establish streaming connection: Get https://stream.launchdarkly.com/all: x509: certificate signed by unknown authority

Kindly advise.

**Comment by brooswit** [comment]
Hi, I'm John from the LaunchDarkly support team. This looks more like a support issue. Could you reach out with this to support@launchdarkly.com please? We would be happy to help out.

**Comment by sumuis** [comment]
https://docs.launchdarkly.com/home/getting-started
